-- CREATE TABLE books (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   title VARCHAR(255) NOT NULL,
--   author VARCHAR(255) NOT NULL,
--   publication_year INT NOT NULL,
--   description VARCHAR(200) NOT NULL,
--   price FLOAT NOT NULL,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- );


-- CREATE TABLE user (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     username VARCHAR(255) NOT NULL,
--     email VARCHAR(255) NOT NULL,
--     password VARCHAR(255) NOT NULL,
--     first_name VARCHAR(255) NOT NULL,      
--     last_name VARCHAR(255) NOT NULL,       
--     date_of_birth DATE NOT NULL,          
--     address VARCHAR(255) NOT NULL,    
--     phone_number VARCHAR(20) NOT NULL,    
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--     isAdmin BOOLEAN DEFAULT FALSE
-- );